apiVersion: v1
kind: Service
metadata:
  name: sbdemo
  labels:
    app: sbdemo
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: sbdemo
  type: LoadBalancer
